import pandas as pd
import matplotlib.pyplot as plt
history=pd.read_csv("training_history.csv")
plt.figure(figsize=(8,5))
plt.plot(history["Epoch"],history["Training Loss"],linewidth=2)
plt.title("Training Loss vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Training Loss")
plt.grid(True)
plt.savefig("training_loss.png")
plt.show()
plt.figure(figsize=(8,5))
plt.plot(history["Epoch"],history["Validation Loss"],linewidth=2)
plt.title("Validation Loss vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Validation Loss")
plt.grid(True)
plt.savefig("validation_loss.png")
plt.show()
plt.figure(figsize=(8,5))
plt.plot(history["Epoch"],history["Training Accuracy"],linewidth=2)
plt.title("Training Accuracy vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Training Accuracy")
plt.grid(True)
plt.savefig("training_accuracy.png")
plt.show()
plt.figure(figsize=(8,5))
plt.plot(history["Epoch"],history["Validation Accuracy"],linewidth=2)
plt.title("Validation Accuracy vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Validation Accuracy")
plt.grid(True)
plt.savefig("validation_accuracy.png")
plt.show()
print("All training curves successfully generated!")